# Generated by Django 3.2.25 on 2024-07-15 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20240715_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 15, 6, 30, 59, 753758, tzinfo=utc)),
        ),
    ]
