# Generated by Django 3.2.25 on 2024-07-15 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
